name: "CALL-DODGY-ACTION"
on:
  workflow_dispatch:

jobs:
    call-dodgy-action:
        name: "Call dodgy action"
        runs-on: ubuntu-latest
        steps:
            - name: "Call action"
              uses: mcbemlogic/dodgy_action
              with:
                secret_var: ${{ secrets.MY_SECRET_KEY }}

